### ISSUE TITLE
Add a physical close button to side panel

### ISSUE THREAD

**Issue by Andrew-Tierno** [HarkerDev/events-manager#2]

**Comment by iluvredwall** [comment]
yeah, i wanted to get it in the top left with the same dimensions/location as the open button, but i couldnt easily figure out how to space it properly without making the title look weird, so i decided to do more useful things instead :P

**Comment by iluvredwall** [comment]
added by 58dda5f68ca22fab97a52cc89ec86a1dea3f9550
